version: '3'

services:
  library_manager:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: library_manager
    ports:
      - "8080:8080"
    depends_on:
      - library_manager_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - .:/app
    command: ["./mvnw", "spring-boot:run"]

  library_manager_db:
    image: postgres
    container_name: library_manager_db
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - library_manager_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes:
  library_manager_db: